.PHONY: build clean test sync-version docs-check check-translation \
        install-dev verify validate-version check-version-sync test-count \
        python-test \
        release-patch release-minor release-major release-beta

PREFIX ?= /usr/local
BUMP_TYPE ?= patch

# Extract version from dune-project: (version "X.Y.Z") → X.Y.Z
get-version = $(shell sed -n 's/^(version "\([^"]*\)")/\1/p' dune-project)

build:
	dune build

test:
	dune runtest

install: build
	@echo "No binary to install (CLI removed in v0.6.7). Use 'pip install par-runtime' for Python or 'opam install par' for OCaml."

uninstall:
	@echo "No binary to uninstall (CLI removed in v0.6.7)."

clean:
	dune clean

sync-version: ## Sync version from dune-project to Python bindings + regenerate par.opam
	$(eval VER := $(get-version))
	sed -i 's/^version = ".*"/version = "$(VER)"/' bindings/python/pyproject.toml
	sed -i 's/^__version__ = ".*"/__version__ = "$(VER)"/' bindings/python/par_runtime/__init__.py
	dune build
	@echo "Synced version $(VER) to Python bindings + par.opam (regenerated by dune)"

docs-check: ## Run all documentation quality checks
	bash scripts/check_doc_identifiers.sh
	bash scripts/check_translation_sync.sh
	timeout 300 bash scripts/check_doc_links.sh
	@grep -rPl "[\x{4e00}-\x{9fff}]" README.md docs/ --include='*.md' | grep -v DOC-MAINTENANCE | grep -v zh-CN | while read f; do extra=$$(grep -P '[\x{4e00}-\x{9fff}]' "$$f" | grep -v '简体中文'); if [ -n "$$extra" ]; then echo "$$f"; fi; done; exit 0
	@echo "All doc checks passed."

check-translation: ## Check docs/ vs docs/zh/ translation sync (strict: fail if missing/outdated)
	@bash scripts/check_translation_sync.sh --strict

check-install-sh: ## Verify install.sh syntax + help output (mandatory before any tag)
	@bash -n install.sh && echo "OK install.sh syntax valid"
	@bash install.sh --help 2>&1 | head -5 >/dev/null && echo "OK install.sh --help renders"

# ─── Dev Install ──────────────────────────────────────────────────────

install-dev: build ## Build + install .so + sync version + verify Python binding
	install -d $(DESTDIR)$(PREFIX)/lib/par
	# Install sqlite-vec extension next to the par lib directory
	# so the OCaml runtime can find it at runtime via path resolution.
	-cp -f _build/default/lib/ffi/vec0.so $(DESTDIR)$(PREFIX)/lib/par/ 2>/dev/null || true
	-cp -f _build/default/lib/ffi/vec0.dylib $(DESTDIR)$(PREFIX)/lib/par/ 2>/dev/null || true
	$(MAKE) --no-print-directory sync-version
	$(MAKE) --no-print-directory verify

verify: ## Verify Python binding version matches dune-project
	@SRC="$(get-version)"; \
	PYVER=$$(python3 -c "from par_runtime import __version__; print(__version__)" 2>/dev/null || echo ""); \
	if [ "$$SRC" != "$$PYVER" ]; then \
		echo "ERROR: dune-project=$$SRC par_runtime=$$PYVER mismatch"; exit 1; \
	else \
		echo "OK Dev install verified: $$SRC"; \
	fi

# ─── Version Validation ───────────────────────────────────────────────

SEMVER_RE := ^\(0\|\[1-9\][0-9]*\)\.\(0\|\[1-9\][0-9]*\)\.\(0\|\[1-9\][0-9]*\)

validate-version: ## Validate dune-project version is valid semver
	@VERSION="$(get-version)"; \
	if ! echo "$$VERSION" | grep -qE '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[a-zA-Z0-9._-]+)?$$'; then \
		echo "ERROR: Invalid semver: $$VERSION"; exit 1; \
	fi; \
	echo "OK $$VERSION is valid semver"

check-version-sync: validate-version ## Check all 4 version files agree (dune-project, par.opam, pyproject.toml, __init__.py)
	@DUNE="$(get-version)"; \
	OPAM=$$(sed -n 's/^version: "\([^"]*\)"/\1/p' par.opam); \
	PY=$$(sed -n 's/^version = "\([^"]*\)"/\1/p' bindings/python/pyproject.toml); \
	INIT=$$(sed -n 's/^__version__ = "\([^"]*\)"/\1/p' bindings/python/par_runtime/__init__.py); \
	if [ "$$DUNE" != "$$PY" ] || [ "$$DUNE" != "$$INIT" ] || [ "$$DUNE" != "$$OPAM" ]; then \
		echo "ERROR: Version mismatch:"; \
		echo "  dune-project:   $$DUNE"; \
		echo "  par.opam:       $$OPAM"; \
		echo "  pyproject.toml: $$PY"; \
		echo "  __init__.py:    $$INIT"; \
		echo "Run 'make sync-version' to fix (regenerates par.opam via dune build)"; exit 1; \
	fi; \
	echo "OK All 4 files agree: $$DUNE"

test-count: ## Run tests and output total count
	@OUTPUT=$$(dune runtest -f 2>&1); \
	echo "$$OUTPUT"; \
	COUNT=$$(echo "$$OUTPUT" | grep -oP '\d+(?= tests? run\.)' | awk '{s+=$$1} END {print s}'); \
	if [ -z "$$COUNT" ]; then COUNT=unknown; fi; \
	echo ""; echo "TEST_COUNT=$$COUNT"

python-test: ## Run Python binding tests via pytest
	cd bindings/python && python3 -m pytest tests/ -v

# ─── Release Automation (scripts/release-bump.sh enforces Pre-Bump Gate) ───

release-patch: validate-version ## Bump patch (X.Y.Z → X.Y.Z+1). Use FORCE=1 to skip gate.
	@bash scripts/release-bump.sh patch $(if $(FORCE),--force,)
	$(MAKE) --no-print-directory install-dev

release-minor: validate-version ## Bump minor (X.Y.Z → X.Y+1.0). Use FORCE=1 to skip gate.
	@bash scripts/release-bump.sh minor $(if $(FORCE),--force,)
	$(MAKE) --no-print-directory install-dev

release-major: validate-version ## Bump major (X.Y.Z → X+1.0.0). Use FORCE=1 to skip gate.
	@bash scripts/release-bump.sh major $(if $(FORCE),--force,)
	$(MAKE) --no-print-directory install-dev

release-beta: validate-version ## Set beta with today's date (BUMP_TYPE=patch|minor|major)
	@bash scripts/release-bump.sh beta $(BUMP_TYPE)
	$(MAKE) --no-print-directory install-dev
